### ISSUE TITLE
Fix About text

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-checker#13]
remove 

> The MultilingualWeb project is exploring standards and best practices that support the creation, localization and use of multilingual web-based information. This project is funded by the European Commission through the ICT PSP Grant Agreement No. 250500, and as part of the Competitiveness and Innovation Framework Programme. Partners in the project are providing feedback on the Internationalization Checker.

fix link for 

> The Internationalization Interest Group operates via a set of public mailing lists supporting the activity of the Internationalization Working Groups. Anyone can participate in the Interest Group by simply joining the mailing list.

remove pre-release for

> The checker is currently a pre-release version, so please let us know about bugs and missing features using the feedback form. We already have plans to add a number of new features over the coming months, and to translate the user interface.

and point the feedback link to the github issues list

**Comment by r12a** [comment]
fixed by https://github.com/w3c/i18n-checker/commit/c81dfadc4043f3e49f8e017c241dadcfc66b6a99

**Comment by tripu** [comment]
I think c81dfadc4043f3e49f8e017c241dadcfc66b6a99 does not link to this GH repo.

**Comment by tripu** [comment]
Apart from pointing here for feedback/bugs, I'd like to say explicitly that &ldquo;this software is free / open source, licenced under the terms of [LICENCE]. The source code is available on GitHub; follow [LINK TO INSTRUCTIONS] to install / compile / test&rdquo; etc.

**Comment by r12a** [comment]
There's a download link in the footer that points here. We could add some more text to the About page if you want.

**Comment by tripu** [comment]
> *&ldquo;We could add some more text to the About page if you want.&rdquo;*

@r12a: yes, please.

I think the data [I mentioned](https://github.com/w3c/i18n-checker/issues/13#issuecomment-240561093) is a necessary minimum.

--

Links to the GH repository corresponding to a site/tool are usually labelled &ldquo;fork this project&rdquo;, &ldquo;GitHub project&rdquo;, &ldquo;source code&rdquo;, etc; when I click &ldquo;download&rdquo; I expect to be taken to a download page, or directly to a binary. So I'd change that text.

--

There are links [&ldquo;feedback form&rdquo;](https://validator.w3.org/i18n-checker/feedback.html) and [&ldquo;feedback&rdquo;](https://www.w3.org/International/2007/06/surveyform-110707.php?docname=http%3A%2F%2Fvalidator.w3.org%2Fi18n-checker&referer=http%3A%2F%2Fvalidator.w3.org%2Fi18n-checker) (in the footer), and both are broken. I suggest those point to [`https://github.com/w3c/i18n-checker/issues`](https://github.com/w3c/i18n-checker/issues).

**Comment by r12a** [comment]
> Links to the GH repository corresponding to a site/tool are usually labelled “fork this project”, “GitHub project”, “source code”, etc; when I click “download” I expect to be taken to a download page, or directly to a binary. So I'd change that text.

changed by https://github.com/w3c/i18n-checker/commit/1a0779e1ac62bdeddd84328eff4e127f8f79550c

> There are links “feedback form” and “feedback” (in the footer), and both are broken. I suggest those point to https://github.com/w3c/i18n-checker/issues.

fixed the former by https://github.com/w3c/i18n-checker/commit/6361ef7826ffe53a9c7a51bc16b9dfb17cb5f054

the latter is already done.  Perhaps you are looking at the currently live version of the checker?  You should run the latest github version.

**Comment by tripu** [comment]
Thanks @r12a!

I'll close this issue now, although I think we should extend the &ldquo;about&rdquo; with what I mentioned&nbsp;&mdash;&nbsp;at some point.

**Comment by r12a** [comment]
> I think we should extend the “about” with what I mentioned — at some point.

i believe that's already done

**Comment by tripu** [comment]
You're right, @r12a.

I just found a couple minor issues reviewing that, and submitted #47 to fix them.
