### ISSUE TITLE
Write “README” with basic info

### ISSUE THREAD

**Issue by tripu** [w3c/i18n-checker#20]
Including:

* [x] Brief description of the project.
* [x] Pointer to [`validator.w3.org/i18n-checker`](https://validator.w3.org/i18n-checker/).
* [x] Licence.
* [x] Dependencies, and instructions to build / compile / install / test.
* [x] How to contribute (usage of branches, PRs); cf #21.

**Comment by r12a** [comment]
We should also point to the list of current checks and tests at https://www.w3.org/International/quicktips/checker

**Comment by r12a** [comment]
> Brief description of the project.
> 
> Pointer to validator.w3.org/i18n-checker.

Done.

**Comment by r12a** [comment]
> We should also point to the list of current checks and tests at https://www.w3.org/International/quicktips/checker

done.

**Comment by tripu** [comment]
Thanks, @r12a. I just updated the description of the issue to keep track of those items.

**Comment by r12a** [comment]
added link to licence, and to installation notes, and noted need to use PRs and run tests

unless there is more to do, i suggest we close this issue

**Comment by tripu** [comment]
Brilliant, thanks!
