### ISSUE TITLE
Start using branches appropriately

### ISSUE THREAD

**Issue by tripu** [w3c/i18n-checker#21]
My suggestion is that we use always a new branch to make improvements, and to fix bugs. No single commit is made to the *default* branch (`master`) without peer review; ie, everything goes through a PR assigned to a person who is not the author of the changes. Changes are merged to `master` only when the reviewer is OK with them.

Document briefly in the “README” (cf #20).

**Comment by r12a** [comment]
brief documentation added to readme in https://github.com/w3c/i18n-checker/commit/0be2d184ae294f6cc0afc09865a0315cd841a342

we plan to adopt this process after the next release is complete.

reopen this issue if more is needed on this topic.

**Comment by tripu** [comment]
There's no harm in committing to `master` only via PRs and forks/branches starting today :)
