### ISSUE TITLE
if the page is in Arabic, Hebrew, Urdu, Persian, Thaana, check that it starts with dir on html or body

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-checker#27]
this depends on language recognition

**Comment by r12a** [comment]
done at https://github.com/w3c/i18n-checker/commit/94a11eba32f67763737ad8095700a73392935034

emits the message for the following language tags: ar, fa, ur, ckb, he, ug, div, ps, nqo, syr
and for any language tag that includes the `Arab` script tag

**Comment by sideshowbarker** [comment]
> emits the message for the following language tags: ar, fa, ur, ckb, he, ug, dv, ps, nqo, syr

Why not for `azb`, `pnb`, `sd`?

**Comment by r12a** [comment]
actually `sd` is there, but i did forget to add the other two. Now fixed https://github.com/w3c/i18n-checker/commit/97647d1b77f008dce3fa6191cb76cad7315a6421. Thanks.
