### ISSUE TITLE
Text missing in UTF-8 BOM disagrees with another declaration

### ISSUE THREAD

**Issue by stevenatkin** [w3c/i18n-checker#49]
In the Explanation section it likes there is supposed to be a list  but I see only %1

**Comment by r12a** [comment]
Yes, that's correct. Those lists are filled in when you run the checker against a particular page (which is why they aren't filled in in the page you looked at).  Would you like me to add a note to that effect at the top of the page?

**Comment by stevenatkin** [comment]
That's right I got confused. I agree we should probably add a comment to tell people that.

**Comment by r12a** [comment]
added a para to the start of the document to explain %1

see https://github.com/w3c/i18n-checker/commit/176ce0457f884bf528c35d55fd6759cd1f2fb971
