### ISSUE TITLE
i18n Checker page does not display properly on Safari on Mac

### ISSUE THREAD

**Issue by stevenatkin** [w3c/i18n-checker#50]
Page does not display properly in Safari. See attached image.
<img width="977" alt="screen shot 2016-09-01 at 8 09 30 am" src="https://cloud.githubusercontent.com/assets/4265395/18166876/9e107f5e-701b-11e6-85a1-977745008ace.png">

**Comment by r12a** [comment]
this is likely to be an https issue - i'll investigate

**Comment by tripu** [comment]
The JavaScript console, or network monitor, on Safari will tell us what's missing/wrong there, @stevenatkin.
You can paste here the output if you want.

**Comment by r12a** [comment]
it should be working ok now.  I changed http:// to https:// for stylesheet and script includes, and added the images that were missing.

**Comment by r12a** [comment]
reopen this if you still have problems

**Comment by stevenatkin** [comment]
Looks good to me now.
