### ISSUE TITLE
Show version number, or release, somewhere on the UI

### ISSUE THREAD

**Issue by tripu** [w3c/i18n-checker#51]
To better track bugs, and signal new releases.

**Comment by r12a** [comment]
i'm writing a versions.php page that lists changes for new versions. It will be linked to from the footer of each page...

**Comment by r12a** [comment]
fixed by creating a change log page (www/versions.php) and linking to it from the page footer

see https://github.com/w3c/i18n-checker/commit/00bce4454916a65147371a2bd1204c2f1bb98d13
