### ISSUE TITLE
Print Friendly

### ISSUE THREAD

**Issue by nitinkaveriappa** [w3c/i18n-checker#69]
Making the website more printer friendly would help to print or save the results of our testing as pdf. Currently the page seems to be very disorderly when you want to print it.

**Comment by r12a** [comment]
@nitinkaveriappa can you provide a picture of what you mean by disorderly?  Thanks. When i created a PDF it doesn't look very stylish, but it seems quite readable.  

(On the other hand, we should probably expand the hidden report text for print.)
